"""Add status to project_understanding

Revision ID: 074c1a7110fd
Revises: 1c90550b42db
Create Date: 2026-04-10 23:15:08.057629
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '074c1a7110fd'
down_revision = '1c90550b42db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_understanding', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_understanding', 'status')
    # ### end Alembic commands ###