"""Add project_understanding

Revision ID: 1c90550b42db
Revises: 785ca3dd63b1
Create Date: 2026-04-10 22:59:33.466422
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1c90550b42db'
down_revision = '785ca3dd63b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###